version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    restart: always
    env_file:
      - .env
  db:
    image: postgres:15
    container_name: telegram_bot_db
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test-tg-bot
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

volumes:
  db_data:
