version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file:
      - .env
  db:
    image: postgres:15
    container_name: telegram_bot_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "0.0.0.0:5432:5432"
    env_file:
      - .env

volumes:
  db_data:
